//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.13 at 03:11:59 PM BRST 
//


package br.inf.portalfiscal.cte;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.inf.portalfiscal.cte package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.inf.portalfiscal.cte
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Ide.Toma03 }
     * 
     */
    public TCTe.InfCte.Ide.Toma03 createTCTeInfCteIdeToma03() {
        return new TCTe.InfCte.Ide.Toma03();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Fluxo }
     * 
     */
    public TCTe.InfCte.Compl.Fluxo createTCTeInfCteComplFluxo() {
        return new TCTe.InfCte.Compl.Fluxo();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.ComData }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.ComData createTCTeInfCteComplEntregaComData() {
        return new TCTe.InfCte.Compl.Entrega.ComData();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfDoc.InfNF }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfDoc.InfNF createTCTeInfCteInfCTeNormInfDocInfNF() {
        return new TCTe.InfCte.InfCTeNorm.InfDoc.InfNF();
    }

    /**
     * Create an instance of {@link TCTe }
     * 
     */
    public TCTe createTCTe() {
        return new TCTe();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntPap }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntPap createTCTeInfCteInfCTeNormDocAntEmiDocAntIdDocAntIdDocAntPap() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntPap();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Peri }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Peri createTCTeInfCteInfCTeNormPeri() {
        return new TCTe.InfCte.InfCTeNorm.Peri();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Cobr.Fat }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Cobr.Fat createTCTeInfCteInfCTeNormCobrFat() {
        return new TCTe.InfCte.InfCTeNorm.Cobr.Fat();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt createTCTeInfCteInfCTeNormDocAntEmiDocAntIdDocAnt() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.ObsCont }
     * 
     */
    public TCTe.InfCte.Compl.ObsCont createTCTeInfCteComplObsCont() {
        return new TCTe.InfCte.Compl.ObsCont();
    }

    /**
     * Create an instance of {@link TImp }
     * 
     */
    public TImp createTImp() {
        return new TImp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.NoInter }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.NoInter createTCTeInfCteComplEntregaNoInter() {
        return new TCTe.InfCte.Compl.Entrega.NoInter();
    }

    /**
     * Create an instance of {@link TRetEnviCTe }
     * 
     */
    public TRetEnviCTe createTRetEnviCTe() {
        return new TRetEnviCTe();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.NoPeriodo }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.NoPeriodo createTCTeInfCteComplEntregaNoPeriodo() {
        return new TCTe.InfCte.Compl.Entrega.NoPeriodo();
    }

    /**
     * Create an instance of {@link TRetConsReciCTe }
     * 
     */
    public TRetConsReciCTe createTRetConsReciCTe() {
        return new TRetConsReciCTe();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Emit }
     * 
     */
    public TCTe.InfCte.Emit createTCTeInfCteEmit() {
        return new TCTe.InfCte.Emit();
    }

    /**
     * Create an instance of {@link TUnidCarga }
     * 
     */
    public TUnidCarga createTUnidCarga() {
        return new TUnidCarga();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Dest }
     * 
     */
    public TCTe.InfCte.Dest createTCTeInfCteDest() {
        return new TCTe.InfCte.Dest();
    }

    /**
     * Create an instance of {@link TProtCTe }
     * 
     */
    public TProtCTe createTProtCTe() {
        return new TProtCTe();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfDoc.InfOutros }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfDoc.InfOutros createTCTeInfCteInfCTeNormInfDocInfOutros() {
        return new TCTe.InfCte.InfCTeNorm.InfDoc.InfOutros();
    }

    /**
     * Create an instance of {@link TImp.ICMS20 }
     * 
     */
    public TImp.ICMS20 createTImpICMS20() {
        return new TImp.ICMS20();
    }

    /**
     * Create an instance of {@link TImp.ICMS60 }
     * 
     */
    public TImp.ICMS60 createTImpICMS60() {
        return new TImp.ICMS60();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Ide.Toma4 }
     * 
     */
    public TCTe.InfCte.Ide.Toma4 createTCTeInfCteIdeToma4() {
        return new TCTe.InfCte.Ide.Toma4();
    }

    /**
     * Create an instance of {@link TEndernac }
     * 
     */
    public TEndernac createTEndernac() {
        return new TEndernac();
    }

    /**
     * Create an instance of {@link TImp.ICMS90 }
     * 
     */
    public TImp.ICMS90 createTImpICMS90() {
        return new TImp.ICMS90();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.ComHora }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.ComHora createTCTeInfCteComplEntregaComHora() {
        return new TCTe.InfCte.Compl.Entrega.ComHora();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntEle }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntEle createTCTeInfCteInfCTeNormDocAntEmiDocAntIdDocAntIdDocAntEle() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntEle();
    }

    /**
     * Create an instance of {@link TConsReciCTe }
     * 
     */
    public TConsReciCTe createTConsReciCTe() {
        return new TConsReciCTe();
    }

    /**
     * Create an instance of {@link TEnviCTe }
     * 
     */
    public TEnviCTe createTEnviCTe() {
        return new TEnviCTe();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub.TomaNaoICMS }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub.TomaNaoICMS createTCTeInfCteInfCTeNormInfCteSubTomaNaoICMS() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub.TomaNaoICMS();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Exped }
     * 
     */
    public TCTe.InfCte.Exped createTCTeInfCteExped() {
        return new TCTe.InfCte.Exped();
    }

    /**
     * Create an instance of {@link TEndReEnt }
     * 
     */
    public TEndReEnt createTEndReEnt() {
        return new TEndReEnt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfModal }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfModal createTCTeInfCteInfCTeNormInfModal() {
        return new TCTe.InfCte.InfCTeNorm.InfModal();
    }

    /**
     * Create an instance of {@link TEndereco }
     * 
     */
    public TEndereco createTEndereco() {
        return new TEndereco();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Imp }
     * 
     */
    public TCTe.InfCte.Imp createTCTeInfCteImp() {
        return new TCTe.InfCte.Imp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Fluxo.Pass }
     * 
     */
    public TCTe.InfCte.Compl.Fluxo.Pass createTCTeInfCteComplFluxoPass() {
        return new TCTe.InfCte.Compl.Fluxo.Pass();
    }

    /**
     * Create an instance of {@link CteProc }
     * 
     */
    public CteProc createCteProc() {
        return new CteProc();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCteComp }
     * 
     */
    public TCTe.InfCte.InfCteComp createTCTeInfCteInfCteComp() {
        return new TCTe.InfCte.InfCteComp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.VeicNovos }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.VeicNovos createTCTeInfCteInfCTeNormVeicNovos() {
        return new TCTe.InfCte.InfCTeNorm.VeicNovos();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCteAnu }
     * 
     */
    public TCTe.InfCte.InfCteAnu createTCTeInfCteInfCteAnu() {
        return new TCTe.InfCte.InfCteAnu();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCarga }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCarga createTCTeInfCteInfCTeNormInfCarga() {
        return new TCTe.InfCte.InfCTeNorm.InfCarga();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfDoc.InfNFe }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfDoc.InfNFe createTCTeInfCteInfCTeNormInfDocInfNFe() {
        return new TCTe.InfCte.InfCTeNorm.InfDoc.InfNFe();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.SemData }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.SemData createTCTeInfCteComplEntregaSemData() {
        return new TCTe.InfCte.Compl.Entrega.SemData();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt createTCTeInfCteInfCTeNormDocAntEmiDocAnt() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.ObsFisco }
     * 
     */
    public TCTe.InfCte.Compl.ObsFisco createTCTeInfCteComplObsFisco() {
        return new TCTe.InfCte.Compl.ObsFisco();
    }

    /**
     * Create an instance of {@link TProtCTe.InfProt }
     * 
     */
    public TProtCTe.InfProt createTProtCTeInfProt() {
        return new TProtCTe.InfProt();
    }

    /**
     * Create an instance of {@link TEndeEmi }
     * 
     */
    public TEndeEmi createTEndeEmi() {
        return new TEndeEmi();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.SemHora }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.SemHora createTCTeInfCteComplEntregaSemHora() {
        return new TCTe.InfCte.Compl.Entrega.SemHora();
    }

    /**
     * Create an instance of {@link TImp.ICMS00 }
     * 
     */
    public TImp.ICMS00 createTImpICMS00() {
        return new TImp.ICMS00();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfDoc }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfDoc createTCTeInfCteInfCTeNormInfDoc() {
        return new TCTe.InfCte.InfCTeNorm.InfDoc();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega }
     * 
     */
    public TCTe.InfCte.Compl.Entrega createTCTeInfCteComplEntrega() {
        return new TCTe.InfCte.Compl.Entrega();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS createTCTeInfCteInfCTeNormInfCteSubTomaICMS() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS();
    }

    /**
     * Create an instance of {@link TImp.ICMSOutraUF }
     * 
     */
    public TImp.ICMSOutraUF createTImpICMSOutraUF() {
        return new TImp.ICMSOutraUF();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Receb }
     * 
     */
    public TCTe.InfCte.Receb createTCTeInfCteReceb() {
        return new TCTe.InfCte.Receb();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Cobr }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Cobr createTCTeInfCteInfCTeNormCobr() {
        return new TCTe.InfCte.InfCTeNorm.Cobr();
    }

    /**
     * Create an instance of {@link TImp.ICMSSN }
     * 
     */
    public TImp.ICMSSN createTImpICMSSN() {
        return new TImp.ICMSSN();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Seg }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Seg createTCTeInfCteInfCTeNormSeg() {
        return new TCTe.InfCte.InfCTeNorm.Seg();
    }

    /**
     * Create an instance of {@link TUnidCarga.LacUnidCarga }
     * 
     */
    public TUnidCarga.LacUnidCarga createTUnidCargaLacUnidCarga() {
        return new TUnidCarga.LacUnidCarga();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS.RefNF }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS.RefNF createTCTeInfCteInfCTeNormInfCteSubTomaICMSRefNF() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS.RefNF();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.AutXML }
     * 
     */
    public TCTe.InfCte.AutXML createTCTeInfCteAutXML() {
        return new TCTe.InfCte.AutXML();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCarga.InfQ }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCarga.InfQ createTCTeInfCteInfCTeNormInfCargaInfQ() {
        return new TCTe.InfCte.InfCTeNorm.InfCarga.InfQ();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Rem }
     * 
     */
    public TCTe.InfCte.Rem createTCTeInfCteRem() {
        return new TCTe.InfCte.Rem();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Ide }
     * 
     */
    public TCTe.InfCte.Ide createTCTeInfCteIde() {
        return new TCTe.InfCte.Ide();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm }
     * 
     */
    public TCTe.InfCte.InfCTeNorm createTCTeInfCteInfCTeNorm() {
        return new TCTe.InfCte.InfCTeNorm();
    }

    /**
     * Create an instance of {@link TEndOrg }
     * 
     */
    public TEndOrg createTEndOrg() {
        return new TEndOrg();
    }

    /**
     * Create an instance of {@link TRetEnviCTe.InfRec }
     * 
     */
    public TRetEnviCTe.InfRec createTRetEnviCTeInfRec() {
        return new TRetEnviCTe.InfRec();
    }

    /**
     * Create an instance of {@link TLocal }
     * 
     */
    public TLocal createTLocal() {
        return new TLocal();
    }

    /**
     * Create an instance of {@link TUnidadeTransp.LacUnidTransp }
     * 
     */
    public TUnidadeTransp.LacUnidTransp createTUnidadeTranspLacUnidTransp() {
        return new TUnidadeTransp.LacUnidTransp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Imp.ICMSUFFim }
     * 
     */
    public TCTe.InfCte.Imp.ICMSUFFim createTCTeInfCteImpICMSUFFim() {
        return new TCTe.InfCte.Imp.ICMSUFFim();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.VPrest }
     * 
     */
    public TCTe.InfCte.VPrest createTCTeInfCteVPrest() {
        return new TCTe.InfCte.VPrest();
    }

    /**
     * Create an instance of {@link TCTe.InfCte }
     * 
     */
    public TCTe.InfCte createTCTeInfCte() {
        return new TCTe.InfCte();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl }
     * 
     */
    public TCTe.InfCte.Compl createTCTeInfCteCompl() {
        return new TCTe.InfCte.Compl();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub createTCTeInfCteInfCTeNormInfCteSub() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub();
    }

    /**
     * Create an instance of {@link TImp.ICMS45 }
     * 
     */
    public TImp.ICMS45 createTImpICMS45() {
        return new TImp.ICMS45();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.VPrest.Comp }
     * 
     */
    public TCTe.InfCte.VPrest.Comp createTCTeInfCteVPrestComp() {
        return new TCTe.InfCte.VPrest.Comp();
    }

    /**
     * Create an instance of {@link TUnidadeTransp }
     * 
     */
    public TUnidadeTransp createTUnidadeTransp() {
        return new TUnidadeTransp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Cobr.Dup }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Cobr.Dup createTCTeInfCteInfCTeNormCobrDup() {
        return new TCTe.InfCte.InfCTeNorm.Cobr.Dup();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt createTCTeInfCteInfCTeNormDocAnt() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt();
    }

}
